# Generated by Django 2.2.2 on 2019-06-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_auto_20190608_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='sport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academy.Sport'),
        ),
    ]
