# Generated by Django 2.2.2 on 2019-06-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_auto_20190608_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joueur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomJoueur', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'joueur',
            },
        ),
        migrations.AlterField(
            model_name='equipe',
            name='nomEquipe',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='equipe',
            name='joueurs',
            field=models.ManyToManyField(to='academy.Joueur'),
        ),
    ]
