# Generated by Django 2.2.2 on 2019-06-09 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0005_auto_20190609_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='joueurs',
            field=models.ManyToManyField(blank=True, to='academy.Joueur'),
        ),
    ]
