# Generated by Django 2.2.2 on 2019-06-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_auto_20190609_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='joueur',
            name='equipes',
            field=models.ManyToManyField(blank=True, to='academy.Equipe'),
        ),
    ]
