# Generated by Django 2.2.2 on 2019-06-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_joueur_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='joueurs',
            field=models.ManyToManyField(blank=True, null=True, to='academy.Joueur'),
        ),
    ]
